version: '3.8'
services:
  inventory-db:
    image: postgres:13.22-alpine3.22
    container_name: inventory-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: ecommerce_inventory
    ports:
      - "5434:5432"
    volumes:
      - inventory-db-data:/var/lib/postgresql/data
volumes:
  inventory-db-data: {}