version: '3.8'
services:
  product-db:
    image: mongo:latest
    container_name: product-db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 12345
      MONGO_INITDB_DATABASE: ecommerce_product
    volumes:
      - product-db-data:/data/db
    restart: unless-stopped
volumes:
  product-db-data: {}