server:
  port: 8080
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              uri: lb://auth-service
              predicates:
              - Path=/api/auth-service/**
              metadata:
                  auth: public

            - id: user-service
              uri: lb://user-service
              predicates:
              - Path=/api/user-service/**
              metadata:
                auth: private

            - id: product-service-public
              uri: lb://product-service
              predicates:
                - Path=/api/product-service/public/**
              metadata:
                auth: public
            - id: product-service-private
              uri: lb://product-service
              predicates:
                - Path=/api/product-service/private/**
              metadata:
                auth: private
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/