services:
  auth-db:
    image: postgres:13.22-alpine3.22
    container_name: auth-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ecommerce_auth
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"
    volumes:
      - auth-db-data:/var/lib/postgresql/data
volumes:
  auth-db-data: {}
